// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cadssvkxgbbpeclmtjqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZHNzdmt4Z2JicGVjbG10anFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzE5ODcsImV4cCI6MjA3MTAwNzk4N30.SMaV1V3NY3hPJLRcLFKR-6Hek-kIe4aHdOkYJGh18n0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});